function love.conf(t)
    t.title = "U.B.O (Unknown Bouncing Objects)" -- The title of the window the game is in (string)
    t.author = "Chezrom"                         -- The author of the game (string)
    t.url = "https://github.com/chezrom/ubo"     -- The website of the game (string)
    t.identity = "ubo"          			     -- The name of the save directory (string)
    t.version = "0.8.0"         			     -- The LÖVE version this game was made for (string)
    t.modules.joystick = false                   -- Enable the joystick module (boolean)
    t.modules.audio = false                      -- Enable the audio module (boolean)
    t.modules.sound = false                      -- Enable the sound module (boolean)
    t.modules.physics = false                    -- Enable the physics module (boolean)
end